const Movies = [
  {
    id: 1,
    name: "Breaking Bad",
    rating: 10,
    link: "https://www.netflix.com/in/title/70143836?source=35",
    image: "images/breakigBad.jpg",
  },
  {
    id: 2,
    name: "Stranger Things",
    rating: 9,
    link: "https://www.netflix.com/in/title/80057281?source=35",
    image: "images/strangerThings.jpg",
  },
  {
    id: 3,
    name: "Ozark",
    rating: 8,
    link: "https://www.netflix.com/in/title/80117552?source=35",
    image: "images/ozark.jpg",
  },
  {
    id: 4,
    name: "Fear Street",
    rating: 7,
    link: "https://www.netflix.com/in/title/81334750?source=35",
    image: "images/fearstreet.jpg",
  },
  {
    id: 5,
    name: "Haunting of Bly Manor",
    rating: 6,
    link: "https://www.netflix.com/in/title/81237854?source=35",
    image: "images/hauntingOfBlyManor.jpg",
  },
  {
    id: 6,
    name: "Locke and Key",
    rating: 7,
    link: "https://www.netflix.com/in/title/80241239?source=35",
    image: "images/lockeAndKey.jpg",
  },
  {
    id: 7,
    name: "The Umbrella Academy",
    rating: 7,
    link: "https://www.netflix.com/in/title/80186863?source=35",
    image: "images/umbrellaAcademy.jpg",
  },
  {
    id: 8,
    name: "The Witcher",
    rating: 8,
    link: "https://www.netflix.com/in/title/80189685?source=35",
    image: "images/wicther.jpg",
  },
  {
    id: 9,
    name: "Bodyguard",
    rating: 6,
    link: "https://www.netflix.com/in/title/80235864?source=35",
    image: "images/bodyguard.jpg",
  },
  {
    id: 10,
    name: "Mindhunter",
    rating: 8,
    link: "https://www.netflix.com/in/title/80114855?source=35",
    image: "images/MindHunter.jpg",
  },
  {
    id: 11,
    name: "Dark",
    rating: 10,
    link: "https://www.netflix.com/in/title/80100172?source=35",
    image: "images/Dark.jpg",
  },
  {
    id: 12,
    name: "Chilling Adventures of Sabrina",
    rating: 8,
    link: "https://www.netflix.com/in/title/80223989?source=35",
    image: "images/Chilling.jpg",
  },
  {
    id: 13,
    name: "Black Mirror",
    rating: 10,
    link: "https://www.netflix.com/in/title/70264888?source=35",
    image: "images/BlackMirror.jpg",
  },
  {
    id: 14,
    name: "Jessica Jones",
    rating: 10,
    link: "https://www.netflix.com/in/title/80002311",
    image: "images/JessicaJones.jpg",
  },
  {
    id: 15,
    name: "Daredevil",
    rating: 10,
    link: "https://www.netflix.com/in/title/80018294?source=35",
    image: "images/Daredevil.jpg",
  },
  {
    id: 16,
    name: "The Walking Dead",
    rating: 9,
    link: "https://www.netflix.com/in/title/70177057?source=35",
      image: "images/walkingDead.jpg",
  },
  // {
  //   id: 1,
  //   name: "Cobra Kai",
  //   rating: 7,
  //   link: "https://www.netflix.com/in/title/81002370?source=35",
  // },
  // {
  //   id: 1,
  //   name: "Elite",
  //   rating: 5,
  //   link: "https://www.netflix.com/in/title/80200942",
  // },
  // {
  //   id: 1,
  //   name: "La Casa De Papel",
  //   rating: 8,
  //   link: "https://www.netflix.com/in/title/80192098",
  // },
  // {
  //   id: 1,
  //   name: "Lucifer",
  //   rating: 9,
  //   link: "https://www.netflix.com/in/title/80057918",
  // },
];

export default Movies;
